config/routes.rb
Rails.application.routes.draw do
  
  get '/genres/action', to: 'genres#action' # it should be written first so that resources :genres, :index doesn't overwrite this custom route
  get '/genres/drama', to: 'genres#drama'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#create'
  
  resources :users do
    resources :movies
  end
  
  resources :users, only: [:index, :new, :create, :show]
  resources :genres
  resources :artists
  resources :movies

  
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :movies
    has_many :artists, through: :movies
    validates_presence_of :name

    accepts_nested_attributes_for :movies
    # accepts_nested_attributes_for :artists

    scope :action, -> {where(:name => "action").order(id: :desc).limit(5)} # scope for filtering is the same as class method
    scope :drama, -> {where(:name => "drama").order(id: :asc).limit(1)}

    def artists_attributes(artist_attributes)
        artist_attributes.values.each do |artist_attribute|
            artist = Artist.find_or_create_by(artist_attribute)
            self.artists << artist
        end

    end
        
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :require_login, :set_genre, only: [:show, :edit, :update, :destroy]

  def index
    @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end  

  def create
    @genre = Genre.find_or_create_by(genre_params)
    redirect_to genres_path
  end

  def show
  end

  def action
    @genres = Genre.action # from Genre model scope method
    render :index
  end

  def drama
    @genres = Genre.drama
    render :index
  end

  def edit
  end

  def update
    @genre.update(genre_params)
    redirect_to genres_path
  end

  def destroy
    @genre.destroy
    redirect_to genres_path
  end
    
  private

  def set_genre
    @genre = Genre.find_by(id: params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name, movie_ids:[], artist_ids:[], artists_attributes: [:name, :age, :gender])
  end
end

app/helpers/genres_helper.rb
module GenresHelper

    # def drama_movies(genres)
    #     all_drama_movies = []
    #     genres.each do |genre|
    #         all_drama_movies << genre.movies if movie.genre_name == "drama"
    #     end
    #     all_drama_movies
    # end
end

app/views/genres/_form.html.erb

<%= label_tag :name %>
<%= text_field_tag :name %>
<%= collection_select(:genre, :movie_ids, Movie.all, :id, :title, prompt: :blank) %>
<%= collection_select(:genre, :artist_ids, Artist.all, :id, :name, prompt: :blank) %>
<%= submit_tag %>



app/views/genres/edit.html.erb
<%= form_for @genre do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.collection_select :movie_ids, Movie.all, :id, :title, prompt: :blank %>
<%= f.collection_select :artist_ids, Artist.all, :id, :name, prompt: :blank %>
<%= f.submit %>
<% end %>

app/views/genres/index.html.erb
<h1>Genres</h1>
<div>
<%= link_to "Only dramas |", genres_drama_path%>
<%= link_to "Only actions |", genres_action_path%>
</div>
<ul>
<% @genres.each do |genre| %>
<li><%= genre.name %></li>
<button class="edit"><%= link_to "Edit", edit_genre_path(genre), method: :get %></button>
<button class="delete" ><%= link_to "Delete", { action: "destroy", id: genre.id }, method: :delete, data: {confirm: "Are you sure?"} %></button>
<% end %>
</ul>

<p><%= link_to "Create new genre", new_genre_path %></p>

app/views/genres/new.html.erb
<%= render partial: "/errors", locals: {record: @genre } %>

<%= form_for @genre do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.collection_select(:movie_ids, Movie.all, :id, :title, prompt: :blank) %>
<%= f.collection_select(:artist_ids, Artist.all, :id, :name, prompt: :blank) %>
<%= f.submit %>
<% end %>


<%#= form_tag("/genre") do %>
<%#= render "form"%>
<%# end %>