config/routes.rb
Rails.application.routes.draw do
  
  get '/genres/action', to: 'genres#action' # it should be written first so that resources :genres, :index doesn't overwrite this custom route
  get '/genres/drama', to: 'genres#drama'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#create'
  
  resources :users do
    resources :movies
  end
  
  resources :users, only: [:index, :new, :create, :show]
  resources :genres
  resources :artists
  resources :movies

  
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :movies
    has_many :genres, through: :movies
    validates_presence_of :gender, :age, :name
    validates :age, numericality: {:message => "%{value} seems wrong. Please, enter the age in numbers"}
   # validate :movies_attributes

    accepts_nested_attributes_for :movies
    # accepts_nested_attributes_for :genres

    def genres_attributes(genre_attributes)
        genre_attributes.values.each do |genre_attribute|
            genre = Genre.find_or_create_by(genre_attribute)
            self.genres << genre
        end
    end
    
    # def movies_attributes=(movie_attributes)
    #     self.movie = Movie.where(:name => movie_attributes[:name]).first_or_create do
    #         t.title = movie_attributes[:title]
    #         t.budget = movie_attributes[:budget]
    #         t.duration = movie_attributes[:duration]
    #     end
    # end

    # def movies_attributes=(movies_attributes)
    #     movies_attributes.each do |i, movie_attributes|
    #         if movie_attributes[:title].present?
    #         movie = Movie.find_or_create_by(title: movie_attributes[:title])
    #         if !self.movies.include?(movie)
    #             self.artist_movies.build(movie: movie) # if there is artist_movies joined table
    #         end
    #         # self.movies << movie # shovelling will invoke whole database each time, better use build method
          
    #      # self.movies.build(movie: movie)
    #     end
    #     end
    # end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    before_action :require_login, :set_artist, only: [:show, :edit, :update, :destroy]
  
  def index
    @artists = current_user.artists
  end

  def new
    @artist = Artist.new
  end

  # def create
  #     @artist = Artist.find_or_create_by(artist_params)  
  #     redirect_to artist_path(@artist)
  # end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to @artist
    else
      render :new
    end
  end

  def show
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end
  

  private

  def set_artist
    @artist ||= Artist.find_by(id: params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :gender, :age, movie_ids:[], genre_ids:[], genres_attributes: [:name])
    # name_ids [] for child whereas name_id for parent, name_name for parent attribute
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_artist.html.erb
<%= @artist.name %><br>
<%= @artist.gender %><br>
<%= @artist.age %>

app/views/artists/_form.html.erb
<%= form_for artists do |f| %>
<%= f.label "Name" %>
<%= f.text_field :name %>
<%= f.label "Gender" %>
<%= f.collection_radio_buttons :gender, [[true, 'Male', false, 'Female', false 'Other']], :first, :last %>
<%= f.label "Age" %>
<%= f.number_field :age %>
<%= f.label "Image" %>
<%= f.file_field :image %>

<%= f.fields_for :movies, Movie.new do |movie_b| %>
<%= movie_b.label "Title "%>
<%= movie_b.text_field :title %>
<% end %>

<%= f.collection_check_boxes :movie_ids, Movie.all, :id, :title do |b|%>
<p>
<%= b.label %>
<%= b.check_box %>
</p>
<% end %>
<%= f.submit %>
<% end %>


app/views/artists/index.html.erb
<div>
  <% @artists.each do |artist| %>
    <div><%= link_to artist.name, artist_path(artist) %></div>
  <% end %>
</div>

<p><%= link_to "Add a new artist", new_artist_path %></p>

app/views/artists/new.html.erb
<%= render partial: "/errors", locals: {record: @artist}%>

<h1>Add a new artist</h1>
<%= form_for @artist do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br>
<%= f.label :gender %>
<%= f.text_field :gender %><br>
<%= f.label :age %>
<%= f.text_field :age %><br>
<%= f.label "Select from the list of movies below" %><br>
<%= f.collection_check_boxes :movie_ids, Movie.all, :id, :title, prompt: true %><br>
<%= f.label "Select genre" %><br>
<%= f.collection_select :genre_ids, Genre.all, :id, :name, prompt: true %><br>
<%= f.submit %>
<% end %>

app/views/artists/show.html.erb
<%#= render partial: "/artist", locals: {artist: @artist }%>
<h3>There are in total <%= pluralize(@artist.movies.count, "movie")%> where <%= @artist.name %> has participated </h3>
<ul>
<% @artist.movies.each do |movie| %>
<li><%= link_to movie.title, user_movie_path(movie.user, movie) %></li>
<% end %>
</ul>

<div><%= link_to "Add a new artist", new_artist_path %></div>
<div><%= link_to "Delete #{@artist.name}", {action: "destroy", id: @artist.id }, method: :delete, data: { confirm: "Are you sure? "}%></div>