config/routes.rb
Rails.application.routes.draw do
  
  get '/genres/action', to: 'genres#action' # it should be written first so that resources :genres, :index doesn't overwrite this custom route
  get '/genres/drama', to: 'genres#drama'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#create'
  
  resources :users do
    resources :movies
  end
  
  resources :users, only: [:index, :new, :create, :show]
  resources :genres
  resources :artists
  resources :movies

  
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    before_action :require_login
    before_action :set_movie, only: [:edit, :update, :show, :destroy]
    before_action :set_user
  
  def index
    @movies = current_user.movies
  end

  def new
    @movie = Movie.new
  end

  def create
    # @user = User.find_by(id: params[:movie][:user_id])
    @movie = current_user.movies.build(movie_params)
    # @movie.artist = Artist.find_or_create_by(artist_params)
    # @movie.genre = Genre.find_or_create_by(genre_params)
    if @movie.save
      redirect_to user_movies_path(@movie.user)
    else
      render :new
    end
  end

  def show
    set_user
  end

  def drama
    @movies = Movie.drama
    render :index
  end

  def edit
   set_user
  end

  def update
    @movie.update(movie_params)
    redirect_to user_movie_path(@movie)
  end

  def destroy
    @movie.destroy
    redirect_to user_movies_path
  end
  
  private

  def set_user
    @user ||= User.find_by(params[:user_id]) # return @user if it exists, if nil, finds it
  end

  def set_movie
    @movie = Movie.find_by(id: params[:id])
    # @movie = User.find_by(id: params[:id]).movies.find_by(:id params[:id)
  end

  

  def movie_params
    params.require(:movie).permit(:title, :duration, :budget, :user_id, :artist_id, :genre_id) # parent_id
  end

  def artist_params
    params.require(:artist).permit(:name, :gender, :age)
  end

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/movies_helper.rb
module MoviesHelper
    def expensive_movies(user_movies)
        titles = []
        user_movies.each do |movie|  
            titles << movie.title if movie.budget >= 10000000
        end
        titles.join(", ")
    end
end

app/views/movies/_form.html.erb

<%= label_tag :title %>
<%= f.text_tag :title %><br>
<%= label_tag :duration %>
<%= text_tag :duration %><br>
<%= label_tag :budget %>
<%= number_tag :budget %><br>
<%#= f.file_field(:movie, :image, accept: 'image/png,image/gif,image/jpeg')%>
<%= label_tag "Choose an artist from a list" %><br>
<%= collection_select(:movie, :artist_id, Artist.all, :id, :name, prompt: true) %><br>
<%= label_tag "Choose a genre from a list" %><br>
<%= collection_select(:movie, :genre_id, Genre.all, :id, :name, prompt: "Select a genre") %><br>
<%#= fields_for :genre do |genre_f| %>
<%#= genre_f.label :genre %>
<%#= genre_f.text_field :name %>
<%# end %>
<%#= hidden_field_tag :current_user_id, value: current_user.id %>
<%#= f.hidden_field :genre_id, value: @genre.id %>
<% submit_tag %>

app/views/movies/edit.html.erb


<%= form_for @movie do |f| %>
<%= f.label :title %>
<%= f.text_field :title %><br>
<%= f.label :duration %>
<%= f.text_field :duration %><br>
<%= f.label :budget%>
<%= f.number_field :budget %><br>
<%#= f.file_field(:movie, :image, accept: 'image/png,image/gif,image/jpeg')%>
<%= f.label "Choose an artist from a list" %><br>
<%= f.collection_select(:artist_id, Artist.all, :id, :name, prompt: true) %><br>
<%= f.label "Choose a genre from a list" %><br>
<%= f.collection_select(:genre_id, Genre.all, :id, :name, prompt: "Select a genre") %><br>
<%#= fields_for :genre do |genre_f| %>
<%#= genre_f.label :genre %>
<%#= genre_f.text_field :name %>
<%# end %>
<%#= hidden_field_tag :current_user_id, value: current_user.id %>
<%#= f.hidden_field :genre_id, value: @genre.id %>
<%= f.submit %>
<% end %>

app/views/movies/index.html.erb
<%#= render "form" %>
<h1>All the movies of <%= current_user.first_name %></h1><br>
<div>
  <h2>There are in total <%= pluralize(current_user.movies.count, "movie")%> in your list</h2>
  <% current_user.movies.each.with_index(1) do |movie, index| %>
    <div><h3><%= index %>. <%= link_to movie.title, user_movie_path(movie.user, movie) %></h3></div>
    <button class="edit"><%= link_to "Edit", edit_user_movie_path(movie.user, movie), method: :get %></button>
    <button class="delete"><%= link_to "Delete", {action: "destroy", id: movie.id }, method: :delete, data: { confirm: "Are you sure? "}%></button>
  <% end %>
  <p><%= link_to "Add a new movie", new_user_movie_path(@user) %></p>
  <p>List of expensive movies which budgets are above 100 000 000</p>
  <ul>
  <li><%= expensive_movies(current_user.movies) %></li>
  </ul>
</div>

app/views/movies/new.html.erb
<h2>Add a new movie to <i><%= current_user.first_name %>'s</i> list</h2>

<%= render partial: "/errors", locals: {record: @movie } %>

<%= form_for @movie do |f| %>
<%= f.label :title %>
<%= f.text_field :title %><br>
<%= f.label :duration %>
<%= f.text_field :duration %><br>
<%= f.label :budget%>
<%= f.number_field :budget %><br>
<%#= f.file_field(:movie, :image, accept: 'image/png,image/gif,image/jpeg')%>
<%= f.label "Choose an artist from a list" %><br>
<%= f.collection_select(:artist_id, Artist.all, :id, :name, prompt: true) %><br>
<%= f.collection_select(:genre_id, Genre.all, :id, :name, prompt: "Select a genre") %><br>
<%#= fields_for :genre do |genre_f| %>
<%#= genre_f.label :genre %>
<%#= genre_f.text_field :name %>
<%# end %>
<%#= f.hidden_field :current_user_id, value: current_user.id %>
<%#= f.hidden_field :genre_id, value: @genre.id %>
<%= f.submit "Add a movie" %>
<% end %>

app/views/movies/show.html.erb
<h1>Title: <%= @movie.title %></h1>
<p>Duration: <%= @movie.duration %></p>
<p>Gerne: <%= @movie.genre.name %></p>
<h3>Artist: <%= link_to @movie.artist.name, artist_path(@movie.artist) if @movie.artist %></h3>

<p><%= link_to "All movies", user_movies_path %></p>