config/routes.rb
Rails.application.routes.draw do
  
  get '/genres/action', to: 'genres#action' # it should be written first so that resources :genres, :index doesn't overwrite this custom route
  get '/genres/drama', to: 'genres#drama'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#create'
  
  resources :users do
    resources :movies
  end
  
  resources :users, only: [:index, :new, :create, :show]
  resources :genres
  resources :artists
  resources :movies

  
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<div class="header">
    <div><%= link_to "Home", root_path %></div>
    <% if current_user %>
    
        <div><%= link_to "Movies", movies_path %></div>
        <div><%= link_to "Artists", artists_path %></div>
        <div><%= link_to "Genres", genres_path %></div>
        <div><%= link_to "Log out", logout_path%></div><br>
        <% else %>
        <div><%= link_to "Login", login_path %></div>
       <div><%= link_to "Sign up", new_user_path %></div>
      <% end %> 
</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cinemania</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <main class="wrapper">
    <%= render "layouts/navbar"%>
    <%= yield %>
  </main>
  </body>
  <footer>
    </footer>
</html>